# Generated by Django 2.1.5 on 2019-03-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_healing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='healing',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='healing',
            name='date',
            field=models.DateField(verbose_name='Status date'),
        ),
    ]
